---
Title: "Data Cleaning and Imputation by Austin Hayes"

Author:
  - Name: Austin Hayes

  -  Email: ahayes65@charlotte.edu

  -  Affiliation: University of North Carolina at Charlotte

Date: June 26, 2025

Description: Using NFL Scouting Combine Event scores from 2004 - 2023, we will learn about data cleaning and imputation in Python.

Categories:
  - Interpreting findings
  - Ethics
  - Importing and Reading data
  - Data Cleaning
  - Data Science
  - Pandas
  - Data Imputation


### Data

This Dataset is from the SCORE Network Data Repository. The authors include: Shane Hauk, Michael Schuckers and Robin Lock

Visit the original data page here: https://data.scorenetwork.org/football/nfl-draft-combine.html

The data set contains 6128 rows and 8 columns. Each row represents a player at the NFL Scouting Combine between 2004 and 2023.

Download data: 

Available on the [Intro to Data Cleaning and Imputation by Austin Hayes](https://github.com/schuckers/Charlotte_SCORE_Summer25/tree/main/Data%20for%20Modules/Data%20for%20Intro%20to%20Data%20Cleaning%20and%20Imputation%20by%20Austin%20Hayes): [epl_player_stats_24_25.csv](https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20for%20Intro%20to%20Data%20Cleaning%20and%20Imputation%20by%20Austin%20Hayes/nfl_combine.csv)

---

### Variables and their Descriptions:


<details>
<summary><b>Variable Descriptions</b></summary>

| Variable | Description | 
|----|-------------|
| position | Playing position of the player |
| Round | Round player was drafted in |
| forty | 40-yard dash time |
| vertical | Vertical jump height (inches) |
| bench_reps | 225 bench press reps |
| broad_jump | Broad jump distances (inches) |
| shuttle | 20-yard shuttle time |

</details>

---

## Learning Goals

- Learn about the 3 C's of Data cleaning
- Basic principles of Data Cleaning
- Data Imputation
- Use Pandas for Data Cleaning
- Learning about the Ethics of Data Cleaning

---

# Data Cleaning and the "Three C's"

Data cleaning is an essential part of data science and sports analytics. Most of the time, you need to clean up the dataset before using it because it won't always be in a correct or readable format. This brings us to the "three C's". This is a very important aspect of data science that provides basic guidance on what to look for when undergoing the data cleaning process. 

The three C's stand for:
- Consistent
- Complete
- Correct


_Consistent_: This means that your dataset is correctly formatted in a standardized fashion. All instances are properly formatted into their respective data types and there are no inconsistencies with text casing.

_Complete_: There is no missing data. All missing values have been addressed by filling them with a reasonable substitute, imputation (we will discuss this later) and/or removing the data depending on the context (we will discuss the ethics of this later).

_Correct_: Fixing inconsistent data entrys such as misspelled items, inconceivable outliers and/or ilogical errors such as negative ages.


Let's break these down by diving into the football combine data!

---

# Getting Started

Before we get started let's import pandas so we can read in our data.

NOTE: If one of the import statements does not work, you may need to download the library(s). Visit one of the links below for more information on downloading them.

Pandas: https://pandas.pydata.org/docs/getting_started/install.html 

Numpy: https://numpy.org/install/

Now, lets import our libraries:

In [1]:
# Import necessary libraries

#Import numpy library for numerical operations
import numpy as np

#Import pandas library for data manipulation and analysis
import pandas as pd

In [2]:
# Read the in the NFL Combine data and store it in a DataFrame
combine_data = pd.read_csv('https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20for%20Intro%20to%20Data%20Cleaning%20and%20Imputation%20by%20Austin%20Hayes/nfl_combine.csv')

---

# Consistency and Correctness

Let's start by examining the first 5 rows of data to get a better look.

In [3]:
# Reveal first 5 rows of the dataset
combine_data.head()

position  Round  forty  vertical  bench_reps  broad_jump  three_cone  \
0       QB    NaN   4.79      30.5         NaN       110.0        7.66   
1       RB    NaN   4.50      34.0        21.0       121.0        7.09   
2       QB    NaN   4.60       NaN         NaN         NaN         NaN   
3       QB    NaN   4.95      30.0         NaN       119.0        7.44   
4       WR    NaN   4.78      38.0         NaN       118.0         NaN   

   shuttle  
0     4.41  
1     4.30  
2      NaN  
3     4.34  
4     4.45

Interesting! Looks like in just the first few rows, there are a lot of missing values.

Before we start deciding what to do with these missing values, let's start by checking the consistentcy. Let's check the datatypes for column and make sure that they align with their values.

In [4]:
# Check the data types of each column to ensure they are consistent with the expected data types
combine_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6128 entries, 0 to 6127
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   position    6128 non-null   object 
 1   Round       4023 non-null   float64
 2   forty       5751 non-null   float64
 3   vertical    4965 non-null   float64
 4   bench_reps  4308 non-null   float64
 5   broad_jump  4891 non-null   float64
 6   three_cone  3985 non-null   float64
 7   shuttle     4093 non-null   float64
dtypes: float64(7), object(1)
memory usage: 383.1+ KB


Nice! looks like we don't need to change any of the datatypes for this dataset.

Let's go ahead and check the _correctness_ and consistency of the dataset by checking some of the rows. To do this, let's take a look at the first 50 rows.

After running the code block below, examine the dataset to make sure they are correctly formatted and there are no absurd outliers. We also need to check that there are no misspelled positions or capitalization issues. 

In [5]:
# Let's check the first 50 rows of the dataset to ensure correctness and consistency.
# This will help us identify any potential issues with the data formatting or inconsistencies.
combine_data.head(50)

position  Round  forty  vertical  bench_reps  broad_jump  three_cone  \
0        QB    NaN   4.79      30.5         NaN       110.0        7.66   
1        RB    NaN   4.50      34.0        21.0       121.0        7.09   
2        QB    NaN   4.60       NaN         NaN         NaN         NaN   
3        QB    NaN   4.95      30.0         NaN       119.0        7.44   
4        WR    NaN   4.78      38.0         NaN       118.0         NaN   
5        OT    NaN   5.41      28.0        20.0       104.0        8.24   
6        WR    NaN   4.76      31.5         NaN       116.0        7.41   
7        WR    NaN   4.73      38.0         NaN       128.0        7.10   
8        WR    NaN   4.59      28.5         NaN       111.0        7.24   
9        RB    NaN   4.71      31.5        16.0       108.0         NaN   
10       QB    NaN   4.87      26.5         NaN       110.0        7.69   
11       WR    NaN   4.61      32.5         NaN       118.0        7.16   
12       WR    NaN   4.50       NaN         NaN         NaN         NaN   
13        C    NaN   4.98      30.5        28.0       105.0        7.84   
14       OG    NaN   5.67      23.0        18.0        94.0        8.25   
15       OG    NaN   5.54      26.5        27.0       101.0        8.12   
16       QB    NaN   4.83      30.5         NaN       113.0        7.28   
17       RB    NaN   4.68      34.5        25.0       120.0        7.44   
18       OG    NaN   5.50      26.5        21.0        98.0        8.01   
19       RB    NaN   4.54      33.5        13.0       112.0        7.27   
20       WR    NaN   4.60      31.0         NaN       117.0        6.72   
21       RB    NaN   4.83      30.5        14.0       108.0         NaN   
22       OG    NaN   6.05       NaN         NaN         NaN        8.03   
23       WR    NaN   4.69      35.0         NaN       112.0         NaN   
24       QB    NaN   4.95       NaN         NaN         NaN         NaN   
25       OG    NaN   5.10       NaN        32.0         NaN         NaN   
26        C    NaN   5.25       NaN        19.0        85.0        8.31   
27       WR    NaN   4.56      33.0         NaN       117.0        7.38   
28       TE    NaN   4.89       NaN        12.0       102.0         NaN   
29       WR    NaN   4.46      31.0         NaN       113.0         NaN   
30        C    NaN   5.84      24.0         NaN        93.0        8.09   
31       OG    NaN   5.82      25.5        21.0        93.0        8.38   
32       FB    NaN   4.97      32.5        22.0       114.0        7.50   
33       TE    NaN   4.84      30.0        19.0       106.0        7.51   
34       WR    NaN   4.62      37.0         NaN       121.0        7.06   
35       TE    NaN   5.03       NaN        21.0       114.0        7.33   
36       RB    NaN   4.70      30.5        21.0       115.0        7.25   
37       WR    NaN   4.65      34.0         NaN       122.0        7.12   
38       RB    NaN   4.64      32.0         NaN       114.0        7.41   
39       TE    7.0   4.89      30.0        17.0       106.0        7.86   
40       OT    1.0   5.49      25.0        27.0        98.0        8.25   
41       OT    4.0   5.07      30.5        34.0       106.0        8.09   
42       OG    5.0   5.22       NaN        26.0         NaN         NaN   
43       RB    2.0   4.37      38.5        25.0       117.0         NaN   
44       WR    3.0   4.58      38.0         NaN       128.0        7.34   
45       OT    6.0   5.11      30.5         NaN       105.0        7.96   
46       OG    1.0   5.33       NaN        30.0         NaN         NaN   
47       WR    5.0   4.36       NaN         NaN         NaN         NaN   
48       RB    NaN   4.51      34.5        22.0       112.0         NaN   
49       OT    6.0   5.44      27.0        22.0       101.0        7.56   

    shuttle  
0      4.41  
1      4.30  
2       NaN  
3      4.34  
4      4.45  
5      4.61  
6       NaN  
7      4.09  
8      4.27  
9       NaN  
10     4.22  
11     4.

Looks quite good! There are no capitalization issues in the position column and all of the numeric values are in float (decimal) format.

This is a massive dataset with over 6000 rows so it may be best to examine it using .describe() from the Pandas library. This will allow us to see statistical information about each column, which will tell us if there are any alarming outliers.

In [6]:
# Check the statistical summary of the dataset to identify any outliers or anomalies
combine_data.describe()

Round        forty     vertical   bench_reps   broad_jump  \
count  4023.000000  5751.000000  4965.000000  4308.000000  4891.000000   
mean      3.832712     4.764519    32.838933    20.721681   114.984870   
std       1.931859     0.305037     4.259617     6.394058     9.325569   
min       1.000000     4.220000    17.500000     2.000000    74.000000   
25%       2.000000     4.530000    30.000000    16.000000   109.000000   
50%       4.000000     4.680000    33.000000    21.000000   116.000000   
75%       5.000000     4.960000    36.000000    25.000000   121.000000   
max       7.000000     6.050000    46.500000    49.000000   147.000000   

        three_cone      shuttle  
count  3985.000000  4093.000000  
mean      7.265425     4.402817  
std       0.406290     0.263690  
min       6.280000     3.750000  
25%       6.970000     4.210000  
50%       7.170000     4.360000  
75%       7.510000     4.560000  
max       9.040000     5.560000

This looks very good; none of the max/min times seem unrealistic. The only number that stands out to me is the bench rep max of 49 reps. This means that somebody holds the record for 49 reps of 225 bench; that's insane! 

FUN FACT: Stephen Paea is the player who had those 49 bench reps at the combine. He was a DT out of Oregan State and was drafted 53rd overall to the Chicago Bears in 2011.

Finally, we need to examine the completeness of the dataset. Before we address this, we need to talk about the ethical decision-making involved with missing data.

---


# Ethics of Data Completeness



We need to consider WHY the data is missing in the first place. Did they mean for it to be empty? Did they forget to record certain datapoints? Sometimes it can be extremely hard to tell so it is crucial to document some of the assumptions your making. Transparency is key for your interpertations so that users/readers understand your thinking process, which may affect the usage of the dataset. Context is everything with data completeness. With that being said, let's start tackling this dataset.



# Completeness

Building upon the previous sections, there are severl ways to approach this issue but let's start by asking: Why is the data missing? If it was intentionally done, why? 

In this case, any mising data is likely due to non-particpation. In more recent years, more and more athletes have started to skip certain drills or the combine altogether. It also depends on what variable we are refering to. For example, most of the missing numerical variables in this case are more than likely non=participation related. However, missing 'Round' numbers most likely means that specific player went undrafted. Missing 'position' values are a little harder to interpret. It may be because a player had no official position coming out of the combine and/or they may have played multiple positions in college. A perfect example of this was Travis Hunter in this year's draft because he had played both Cornerback and Wide Receiver in his college career. In this case, we may want to look at how many rows have missing positions. 

Before getting to that, let's make it simple and split the data. We will make one dataframe of missing values and the other will have complete records only.

In [7]:
# Make a copy of the dataset with no missing values
complete_combine_data = combine_data.dropna()

# Make a dataframe of the missing values
missing_combine_data = combine_data[combine_data.isnull().any(axis=1)]

Let's take a look at the volume of data for each dataframe.

In [8]:
# Display the shapes of the complete and missing dataframes to understand the extent of missing data
complete_combine_data.shape, missing_combine_data.shape

((1930, 8), (4198, 8))

That is a TON of data with missing values. Let's start by examining the rows with any missing position groups.

In [9]:
missing_combine_data[missing_combine_data['position'].isnull()]

Empty DataFrame
Columns: [position, Round, forty, vertical, bench_reps, broad_jump, three_cone, shuttle]
Index: []

That's great! There are no players with missing positions! However, let's just double check that all of them are properly formatted.

In [10]:
# Search every instance of a unique value in order to ensure that all positions are properly formatted
missing_combine_data['position'].unique()

array(['QB', 'RB', 'WR', 'OT', 'C', 'OG', 'TE', 'FB', 'OL', 'OLB', 'CB',
       'DT', 'S', 'DE', 'ILB', 'DL', 'EDGE', 'LB', 'DB'], dtype=object)

Looks good! Moving on to the numeric variables, let's see if there are any rows missing AT LEAST 4 of their combine drill values.

In [11]:
missing_combine_data[missing_combine_data[['forty','vertical','bench_reps','broad_jump','three_cone','shuttle']].isna().sum(axis=1) >= 4]

position  Round  forty  vertical  bench_reps  broad_jump  three_cone  \
2          QB    NaN   4.60       NaN         NaN         NaN         NaN   
12         WR    NaN   4.50       NaN         NaN         NaN         NaN   
24         QB    NaN   4.95       NaN         NaN         NaN         NaN   
25         OG    NaN   5.10       NaN        32.0         NaN         NaN   
42         OG    5.0   5.22       NaN        26.0         NaN         NaN   
...       ...    ...    ...       ...         ...         ...         ...   
6118       CB    7.0   4.51       NaN        18.0         NaN         NaN   
6122       DT    4.0   4.89       NaN         NaN         NaN         NaN   
6124       CB    5.0   4.26      42.0         NaN         NaN         NaN   
6125       DE    3.0    NaN       NaN        15.0         NaN         NaN   
6126       CB    NaN   4.57       NaN         NaN         NaN         NaN   

      shuttle  
2         NaN  
12        NaN  
24        NaN  
25        NaN  
42        NaN  
...       ...  
6118      NaN  
6122      NaN  
6124      NaN  
6125      NaN  
6126      NaN  

[1123 rows x 8 columns]

Wow, there are 1,123 players who had no data for the majority of the combine drills! In this case, these are most likely players that skipped out on certain drills in attempt to prevent injury and/or only do drills that may be neccesary for their position. It is difficult to decide what to do with these players.

Some of the possible options we could take are: drop all rows with missing data, drop ONLY the rows with majority of their data missing, mark the missing data as a certain value, OR change all of the missing drill values to the mean/median. 

Making this decision means we must weigh the pros and cons of each approach for the most faithful representation of the data. You would most likely not want to drop all of rows with missing values in this case because that is the majority of the dataset and causes an obstruction of the truth due to the elimination of a lot of drill values. Dropping players that have not competed in most of the drills could be a good idea but that would mean ignoring the drills that they DID do. On one hand, if you replace all of the data with a certain value such as the mean, it would'nt change the distribution too much. However, on the other hand, it would not be a truly accurate representation because if those players DID particpate in the drill, the outcome may be drastically different. 

Believe it or not, we may need to do several of these approaches. The best approach may be a somewhat subjective one but let's go with this one:

- To address assumpted undrafted players, we will change the column data type to the object type and enter all missing values as undrafted. 
- Players Missing ALL of their drill values will be dropped from the dataset since we only care about players that participated in the draft combine
- Any other missing drill value will be assigned to the mean value of that column in order to perserve drill values that were completed.


Ideally, we would not want to replace all of the missing values with the mean because it does not accurately represent those player TRUE drill results. However, in order to perserve an accurate datatype, float, this is most likely to be the best decision. The reason we changed the datatype of 'round' and not the drill value columns is due to the nature of 'round'. The round a player was drafted in is NOT a measurement. It can be viewed as a categorical variable, much like that of a shoe size. 'Round' may be represented by a number but it is read as a category that indicates when a player was drafted.

Let's start by dropping all players who, we assume, did not particpated in the draft combine.

In [12]:
# Drop rows that are missing all of the combine drill values
missing_combine_data = missing_combine_data.dropna(subset=['forty', 'vertical','bench_reps','broad_jump','three_cone','shuttle'], how='all')

# Check that they are no longer present
missing_combine_data[missing_combine_data[['forty', 'vertical','bench_reps','broad_jump','three_cone','shuttle']].isnull().all(axis=1)]

Empty DataFrame
Columns: [position, Round, forty, vertical, bench_reps, broad_jump, three_cone, shuttle]
Index: []

Nice! Now, let's change the data type of the round drafted column and replace all missing values with 'undrafted'

In [13]:
# Change the column data type to the object type
missing_combine_data['Round'] = missing_combine_data['Round'].astype('object')

# Check that the data type has been changed
missing_combine_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4053 entries, 0 to 6127
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   position    4053 non-null   object 
 1   Round       1995 non-null   object 
 2   forty       3821 non-null   float64
 3   vertical    3035 non-null   float64
 4   bench_reps  2378 non-null   float64
 5   broad_jump  2961 non-null   float64
 6   three_cone  2055 non-null   float64
 7   shuttle     2163 non-null   float64
dtypes: float64(6), object(2)
memory usage: 285.0+ KB


Looks like it is now an object datatype, now replace the missing values.

In [14]:
# Replace the missing values in the 'Round' column with 'undrafted'
missing_combine_data['Round'] = missing_combine_data['Round'].fillna('Undrafted')

In [15]:
# Let's check a sample of the data to ensure that the missing values have been replaced correctly
missing_combine_data.sample(50)

position      Round  forty  vertical  bench_reps  broad_jump  three_cone  \
1857       QB  Undrafted   4.95      29.0         NaN       108.0        7.25   
4146       DE        3.0   4.92       NaN        26.0         NaN         NaN   
2286       QB  Undrafted   5.08      27.0         NaN       105.0        7.32   
5266        S        1.0   4.46      35.5        19.0       128.0         NaN   
3888       DT        1.0   5.12       NaN         NaN         NaN         NaN   
4628      ILB        5.0   4.66       NaN        20.0       113.0         NaN   
1829       WR        2.0   4.60      39.0         NaN       127.0        7.00   
1718       QB        6.0   4.84      30.5         NaN       106.0        7.33   
194        OG  Undrafted   5.51      27.5         NaN        99.0         NaN   
213        WR  Undrafted   4.46      37.0         NaN       124.0        7.21   
1586       WR        6.0   4.43      31.5        12.0       120.0         NaN   
365        QB  Undrafted   5.12      27.5         NaN        94.0        7.97   
2425       TE        5.0    NaN       NaN        14.0         NaN         NaN   
5279       CB  Undrafted   4.60      31.5         5.0       114.0        6.94   
3374       CB        4.0   4.50      37.5         NaN       122.0         NaN   
5704       CB  Undrafted    NaN       NaN        21.0         NaN         NaN   
4520       CB  Undrafted   4.63       NaN         7.0         NaN         NaN   
5135       CB        3.0   4.49       NaN        17.0         NaN         NaN   
419        RB        5.0   4.67      35.0         NaN       114.0        7.03   
3287       CB        1.0   4.34      41.0        15.0       128.0         NaN   
2860       WR        6.0   4.35      36.5         NaN       125.0        7.28   
195        QB  Undrafted   5.08      29.0         NaN       111.0        7.24   
5934       DL        1.0   4.52      35.3        36.0       118.0         NaN   
5883       DB  Undrafted   4.85      28.5         NaN       110.0        7.44   
5310     EDGE  Undrafted   4.83      31.5        26.0         NaN        7.21   
2266       WR  Undrafted   4.58      37.5         NaN       119.0        6.95   
2853       WR  Undrafted   4.45      36.5         NaN       125.0         NaN   
5922       DT        5.0   4.90      28.5         NaN       106.0        7.68   
1654       WR  Undrafted   4.46      33.5        20.0       119.0        7.10   
1371       RB  Undrafted   4.67      33.5        21.0       110.0        7.26   
2284       QB  Undrafted   4.93      34.5         NaN       123.0        6.96   
1795       WR  Undrafted   4.60      36.0        20.0       124.0        7.07   
1514       OG        5.0   5.29      27.0         NaN       102.0        7.87   
343        WR        1.0   4.32       NaN         NaN         NaN        6.99   
3522      ILB        2.0   4.62      34.0        23.0       114.0        7.47   
2882       WR  Undrafted   4.48      39.5        29.0       125.0        7.00   
4236       DT        3.0   5.01       NaN         NaN         NaN         NaN   
1325       WR  Undrafted   4.56      33.5         NaN       118.0        6.46   
5783       LB  Undrafted   4.59       NaN        18.0       119.0         NaN   
2102       TE        2.0   4.79       NaN        13.0         NaN         NaN   
3787        S        7.0   4.49      37.5        15.0         NaN         NaN   
1073        C  Undrafted   5.04       NaN        33.0         NaN         NaN   
2323       WR  Undrafted   4.51      35.0        10.0       113.0        6.99   
1664       WR        5.0   4.38      33.5        16.0       124.0         NaN   
3214        C        4.0   4.94      33.0         NaN       118.0        7.32   
1972       RB        3.0   4.61      31.5        20.0       112.0         NaN   
1447       OG  Undrafted   5.12      31.5        22.0       108.0        7.87   
4239        S  Undrafted   4.53      37.0        12.0       122.0         NaN   
631        QB  Undrafted   4.83     

Looks great! Now we need to enter the rest of the missing values as the mean of their respective columns.

In [16]:
# Replace all values in the 'forty', 'vertical', 'bench_reps', 'broad_jump', 'three_cone', and 'shuttle' columns that are missing with the mean of their respective columns
# This will help us maintain the integrity of the data while filling in the gaps.

# 'forty' column
missing_combine_data['forty'] = missing_combine_data['forty'].fillna(missing_combine_data['forty'].mean())

# 'vertical' column
missing_combine_data['vertical'] = missing_combine_data['vertical'].fillna(missing_combine_data['vertical'].mean())

# 'bench_reps' column
missing_combine_data['bench_reps'] = missing_combine_data['bench_reps'].fillna(missing_combine_data['bench_reps'].mean())

# 'broad_jump' column
missing_combine_data['broad_jump'] = missing_combine_data['broad_jump'].fillna(missing_combine_data['broad_jump'].mean())

# 'three_cone' column
missing_combine_data['three_cone'] = missing_combine_data['three_cone'].fillna(missing_combine_data['three_cone'].mean())

# 'shuttle' column
missing_combine_data['shuttle'] = missing_combine_data['shuttle'].fillna(missing_combine_data['shuttle'].mean())

Let's check a sample of the data to take a look at the results of our operations.

In [17]:
missing_combine_data.sample(50)

position      Round     forty   vertical  bench_reps  broad_jump  \
3340      OLB        7.0  4.710000  32.733213   24.000000  106.000000   
1506       WR        6.0  4.370000  33.000000   17.000000  125.000000   
4767       CB  Undrafted  4.690000  33.500000   20.000000  118.000000   
1690       QB        4.0  4.950000  28.500000   20.044996  112.000000   
855        WR  Undrafted  4.460000  33.500000   20.044996  115.086795   
3428       DT  Undrafted  4.910000  32.500000   35.000000  115.000000   
3372      OLB        2.0  4.570000  38.500000   26.000000  129.000000   
3112       OG  Undrafted  5.440000  26.000000   25.000000   95.000000   
1063       RB  Undrafted  4.700000  35.000000   18.000000  117.000000   
231        OG        4.0  4.930000  32.733213   20.044996  115.086795   
2168       RB        6.0  4.600000  32.000000   15.000000  113.000000   
5241      ILB  Undrafted  4.762214  33.000000   23.000000  118.000000   
569        TE        5.0  4.780000  35.000000   20.044996  116.000000   
24         QB  Undrafted  4.950000  32.733213   20.044996  115.086795   
3266      OLB  Undrafted  4.580000  37.000000   24.000000  112.000000   
2677       QB        4.0  4.810000  31.000000   20.044996  110.000000   
4638       DE        5.0  4.780000  32.733213   30.000000  115.086795   
1976       RB        4.0  4.420000  34.500000   20.044996  118.000000   
2462       OT        1.0  4.762214  28.500000   24.000000  105.000000   
343        WR        1.0  4.320000  32.733213   20.044996  115.086795   
1055       WR  Undrafted  4.600000  36.000000   14.000000  115.000000   
894        TE        3.0  4.610000  32.733213   28.000000  115.086795   
365        QB  Undrafted  5.120000  27.500000   20.044996   94.000000   
2938       TE  Undrafted  4.980000  29.500000   16.000000  112.000000   
1751       RB        4.0  4.580000  31.500000   20.044996  118.000000   
3283       DT  Undrafted  5.090000  26.500000   19.000000  104.000000   
3258      OLB  Undrafted  4.580000  34.500000   22.000000  118.000000   
3906       DE        6.0  4.840000  32.733213   21.000000  117.000000   
6028       CB        4.0  4.460000  36.000000   20.044996  129.000000   
4697       CB        3.0  4.410000  35.000000   14.000000  125.000000   
3495      OLB        5.0  4.780000  32.733213   20.044996  115.086795   
5684       DL        3.0  4.790000  32.733213   23.000000  115.086795   
2934       OL  Undrafted  5.270000  24.000000   12.000000   99.000000   
863        OT  Undrafted  5.450000  32.733213   19.000000  115.086795   
4348      ILB  Undrafted  4.870000  30.000000   27.000000  113.000000   
463        WR        5.0  4.490000  32.733213   20.044996  115.086795   
74         WR        5.0  4.530000  41.000000   20.044996  131.000000   
2106       QB        5.0  4.780000  32.500000   20.044996  113.000000   
1460       OG        4.0  5.020000  32.733213   26.000000  115.086795   
470         C  Undrafted  5.550000  25.000000   20.000000   90.000000   
1428       RB  Undrafted  4.580000  32.733213   20.000000  115.086795   
1010       WR        3.0  4.520000  32.733213   20.044996  115.086795   
5939       LB        3.0  4.580000  32.000000   20.044996  121.000000   
2641       WR  Undrafted  4.630000  34.000000    8.000000  113.000000   
3223       WR        2.0  4.360000  38.500000   20.044996  136.000000   
3655        S        7.0  4.630000  38.000000   20.044996  127.000000   
5937        S  Undrafted  4.650000  35.500000   18.000000  119.000000   
1599       OT        5.0  5.070000  28.500000   20.044996  112.000000   
1079       WR        5.0  4.490000  32.733213   12.000000  115.086795   
5817       DT  Undrafted  5.060000  30.000000   27.000000  101.000000   

      three_cone   shuttle  
3340    7.275134  4.411082  
1506    7.080000  4.411082  
4767    7.010000  4.200000  
1690    7.220000  4.390000  
855     7.275134  4.411082  
3428    7.230000  4.200000  
3372    7.275134  4.000000  
3112    7.970000  4.910000  
1063    6.850000  4.

Nice! Finally, let's go ahead and double-check that there are no more rows with missing values!

In [18]:
# Count up missing values in each column to ensure that all missing values have been addressed
missing_combine_data.isna().sum()

position      0
Round         0
forty         0
vertical      0
bench_reps    0
broad_jump    0
three_cone    0
shuttle       0
dtype: int64

Beatiful! Now let's complete the final step of this process and combine the complete and missing datasets back together!

In [19]:
# Lets combine the complete and missing datasets back together
Final_combine_data = pd.concat([complete_combine_data, missing_combine_data], ignore_index=True)

Let's check it out!

In [20]:
Final_combine_data.tail(50)

position      Round     forty   vertical  bench_reps  broad_jump  \
5933       CB        5.0  4.330000  39.500000   20.044996  132.000000   
5934       CB        2.0  4.500000  32.733213   20.044996  115.086795   
5935       CB        1.0  4.440000  32.733213   20.044996  115.086795   
5936       LB        5.0  4.762214  32.733213   21.000000  115.086795   
5937        S  Undrafted  4.762214  35.000000   16.000000  120.000000   
5938        S  Undrafted  4.520000  32.733213   20.044996  124.000000   
5939       LB  Undrafted  4.760000  40.500000   20.044996  133.000000   
5940       DT        5.0  4.762214  32.733213   29.000000  115.086795   
5941     EDGE        2.0  4.550000  35.000000   20.044996  122.000000   
5942        S  Undrafted  4.762214  35.000000   15.000000  125.000000   
5943       DE        2.0  4.770000  37.500000   20.044996  123.000000   
5944       DT  Undrafted  5.300000  27.000000   20.044996  100.000000   
5945        S        2.0  4.762214  35.000000   16.000000  115.086795   
5946       DT        5.0  5.300000  32.733213   20.044996  101.000000   
5947     EDGE        5.0  4.720000  41.000000   25.000000  121.000000   
5948       LB        6.0  4.520000  39.500000   20.044996  120.000000   
5949       LB  Undrafted  4.762214  34.000000   20.044996  121.000000   
5950       LB  Undrafted  4.790000  31.000000   20.044996  109.000000   
5951       LB  Undrafted  4.730000  34.500000   20.000000  114.000000   
5952     EDGE        3.0  4.670000  33.000000   20.044996  120.000000   
5953       LB  Undrafted  4.670000  32.000000   20.044996  120.000000   
5954       LB        4.0  4.520000  37.500000   20.044996  128.000000   
5955     EDGE        5.0  4.860000  34.000000   20.044996  117.000000   
5956       LB        7.0  4.600000  36.000000   20.044996  122.000000   
5957       CB  Undrafted  4.480000  37.500000   20.044996  126.000000   
5958       DE  Undrafted  4.810000  29.000000   20.044996  115.000000   
5959       CB        2.0  4.360000  34.500000   20.044996  128.000000   
5960       CB        2.0  4.380000  32.733213   20.044996  115.086795   
5961       CB  Undrafted  4.420000  32.733213   20.044996  123.000000   
5962     EDGE        1.0  4.580000  32.733213   27.000000  115.086795   
5963       DE        3.0  4.762214  32.733213   24.000000  115.086795   
5964     EDGE        7.0  4.700000  31.500000   20.044996  117.000000   
5965       CB  Undrafted  4.400000  32.733213   20.044996  115.086795   
5966        S  Undrafted  4.550000  34.000000   17.000000  122.000000   
5967       LB        3.0  4.470000  42.000000   20.044996  129.000000   
5968        S        5.0  4.470000  32.733213   20.044996  122.000000   
5969       DT        4.0  4.762214  33.000000   20.044996  107.000000   
5970       LB        1.0  4.520000  32.000000   20.044996  122.000000   
5971       DE        1.0  4.510000  35.500000   20.044996  123.000000   
5972       CB  Undrafted  4.680000  32.733213   20.044996  115.086795   
5973       CB        7.0  4.510000  32.733213   18.000000  115.086795   
5974       CB        4.0  4.762214  34.500000   17.000000  118.000000   
5975       CB        4.0  4.530000  36.000000   20.044996  124.000000   
5976     EDGE        2.0  4.460000  32.500000   20.044996  123.000000   
5977       DT        4.0  4.890000  32.733213   20.044996  115.086795   
5978        S        3.0  4.360000  39.500000   20.044996  128.000000   
5979       CB        5.0  4.260000  42.000000   20.044996  115.086795   
5980       DE        3.0  4.762214  32.733213   15.000000  115.086795   
5981       CB  Undrafted  4.570000  32.733213   20.044996  115.086795   
5982       DT        1.0  4.770000  29.000000   20.044996  111.000000   

      three_cone   shuttle  
5933    6.480000  3.940000  
5934    7.275134  4.411082  
5935    7.275134  4.411082  
5936    7.275134  4.411082  
5937    7.275134  4.411082  
5938    7.000000  4.411082  
5939    7.090000  4.550000  
5940    7.275134  4.411082  
5941    7.275134  4.

In [21]:
# Examine the column data types of the final combined dataset to ensure they are consistent
Final_combine_data.info()

# print the statistical summary of the final combined dataset
print(Final_combine_data.describe())

# Print the shape of the final combined dataset to confirm that it has been successfully created
print(Final_combine_data.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5983 entries, 0 to 5982
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   position    5983 non-null   object 
 1   Round       5983 non-null   object 
 2   forty       5983 non-null   float64
 3   vertical    5983 non-null   float64
 4   bench_reps  5983 non-null   float64
 5   broad_jump  5983 non-null   float64
 6   three_cone  5983 non-null   float64
 7   shuttle     5983 non-null   float64
dtypes: float64(6), object(2)
memory usage: 374.1+ KB
             forty     vertical   bench_reps   broad_jump   three_cone  \
count  5983.000000  5983.000000  5983.000000  5983.000000  5983.000000   
mean      4.764430    32.820944    20.532236   115.003473     7.268667   
std       0.299064     3.880485     5.434014     8.431625     0.331600   
min       4.220000    17.500000     2.000000    74.000000     6.280000   
25%       4.530000    30.500000    18.000000   111.000000   

In [22]:
# Confirm there are no missing values in the final combined dataset
print(Final_combine_data.isnull().sum())

position      0
Round         0
forty         0
vertical      0
bench_reps    0
broad_jump    0
three_cone    0
shuttle       0
dtype: int64


The data, much like the title of this section, is now 'complete'!

---


# Data Imputation


Data Imputation is an extremely important topic in data cleaning. You may not know what it is yet, but you have actually seen it in this module thus far!

_Data Imputation_: The process of filling in missing data points using estimated/substitute values. 

Do you remember when we replaced all of the missing combine drill values with each columns mean? That's data imputation!

However, that is not the only way to do data imputation. You can use different models to estimate what values to impute for your missing values. If you are new to data modeling or have no experience with it, I'll walk you through it. Model-making is just a way of using pre-existing data to estimate what a value might be. There are seperate models that can be used for categorical and numerical estimates. Today, we will only go over numerical model-making with linear regression. This means that we will be estimating a numerical outcome for one of our variables, such as 40-yard dash time. 


Let's go ahead and start by redoing some steps to setup our missing values dataset from earlier.

In [23]:
# Re-read in the orginal dataset to make sure we are working with the original data
combine_data = pd.read_csv('https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20for%20Intro%20to%20Data%20Cleaning%20and%20Imputation%20by%20Austin%20Hayes/nfl_combine.csv')

# Split the datset into to a complete and missing dataset
# Make a copy of the dataset with no missing values
complete_combine_data_2 = combine_data.dropna()

# Make a dataframe of the missing values
missing_combine_data_2 = combine_data[combine_data.isnull().any(axis=1)]

Now we need to import the necessary libraries for modeling.

Here are some links to download the libraries, if you don't have them downloaded yet.

Sklearn: https://scikit-learn.org/stable/install.html

In [24]:
# Import necessary libraries for modeling
# train_test_split is used to split the dataset into training and testing sets to train the model. 
from sklearn.model_selection import train_test_split

# Import linear regression model
from sklearn.linear_model import LinearRegression


---

# Linear Regression Model for Imputation


As stated earlier, linear regression models are used to estimate a numerical outcome based on other variables. In this lesson I will show how to impute data using this model. 

Linear regression models: Models that assume a linear relationship between predictor variables, meaning the change in the outcome is constant for every unit change in the predictor(s). In other words, Linear regression models assume that there is a linear relationship between predictors on the x-axis and the outcome on the y-axis. If there is an increase in the x-axis, there is an expect change in one direction on the y-axis.

Every model needs to be trained first using complete data in order to make the most accurate assessment. This will reuqire splitting the data into a training dataset. There are various splits you can do such as 50/50, 40/60, 30/70, etc. However, in this case, we have already done the split because we want to use ALL of the complete data points to estimate the missing ones. We could split the complete data, training and testing the model with just that data but we only care about imputing the data with missing points in this case.

In this example, we will use each players combine drills to predict what their missing 40-yard dash time could be.

In [25]:
# Create the linear regression model object
linear_model = LinearRegression()


# Note: For some reason, the model needs a 2d array for the x variable, so we need to use double brackets.
# We will use the complete data set to train the model.
x = complete_combine_data_2[['vertical', 'bench_reps', 'broad_jump', 'three_cone', 'shuttle']]

# unlike x, y can be a 1d array, so we can use single brackets
# We will use the 'forty' column to train the model off of preexisting 40-yard dash times.
y = complete_combine_data_2['forty']

# Fit the model to the training data
linear_model.fit(x, y)

LinearRegression()

In [26]:
missing_combine_data_2.columns

Index(['position', 'Round', 'forty', 'vertical', 'bench_reps', 'broad_jump',
       'three_cone', 'shuttle'],
      dtype='object')

Now that we have built the model and trained it, let's have it guess what every players, who has a missing 40-yard dash time, 40 time is. 

In [27]:
# Gather ONLY the players who have missing 40-yard dash times from the dataset with missing values.
# There can be no missing other missing values within the dataset for the model to work properly.
# Therefore we must ensure that the other columns we are using to predict the 40-yard dash time are not missing.
# Those columns being 'position', 'Round', 'vertical', 'bench_reps', 'broad_jump', 'three_cone', and 'shuttle'.
missing_fortys = missing_combine_data_2[missing_combine_data_2['forty'].isna() & missing_combine_data_2[['position', 'Round', 'vertical', 'bench_reps', 'broad_jump', 'three_cone', 'shuttle']].notna().all(axis=1)]
 #& missing_combine_data_2[cols].notna().all(axis=1)
# Use that data we just created to predict the missing 40-yard dash times
predicted_fortys = linear_model.predict(X=missing_fortys[['vertical', 'bench_reps', 'broad_jump', 'three_cone', 'shuttle']])

print(predicted_fortys)

[5.07133559 4.71745076 4.87740177 4.45985711 4.64774051 5.14412653
 5.08528085 5.09802023 5.09834207 4.9223477  4.51912772 4.64512984
 4.55149641 4.47374944 4.57628351]


Nice! Being that there are 15 predicted values, that means that only 15 players had no missing data EXCEPT for their 40-yard dash times. 

Let's fill the data and combine it back into the missing dataset. Before we begin, let's print out the prexisting amount of NA rows compared to after, to make sure we implement these values correctly.

In [28]:
# Print out the prexisting amount of NA rows compared to after, to make sure we implement these values correctly.
print('Pre-existing amount of NA rows: ', missing_combine_data_2.isna().sum())

Pre-existing amount of NA rows:  position         0
Round         2105
forty          377
vertical      1163
bench_reps    1820
broad_jump    1237
three_cone    2143
shuttle       2035
dtype: int64


As you can see, there are 377 missing values in the 'forty' column.

Now let's impute the values in the missing fortys dataset.

In [29]:
# fill NA values in the missing fortys 
missing_fortys.loc[:,'forty'] = predicted_fortys

In [30]:
# Make sure that the values have been filled in correctly
missing_fortys.sample(15)

position  Round     forty  vertical  bench_reps  broad_jump  three_cone  \
2469       OG    1.0  5.144127      26.5        35.0       105.0        7.65   
313         C    4.0  5.071336      32.0        21.0        96.0        7.57   
2444       RB    2.0  4.459857      40.0        11.0       126.0        7.07   
5610       LB    5.0  4.473749      38.0        17.0       123.0        6.89   
2971       OL    2.0  5.098342      26.5        33.0       105.0        7.53   
3004       OL    5.0  4.922348      30.5        25.0       112.0        7.50   
2607       OL    2.0  5.085281      28.0        29.0       109.0        7.77   
2283       TE    5.0  4.717451      33.0        18.0       114.0        7.12   
2412        C    2.0  4.877402      30.5        21.0       108.0        7.29   
2449       RB    6.0  4.647741      35.0        15.0       120.0        7.13   
5237        S    5.0  4.519128      34.0        14.0       117.0        6.67   
5590        S    2.0  4.551496      35.0        17.0       115.0        6.82   
2665       OT    2.0  5.098020      28.0        27.0       108.0        7.77   
5997       LB    3.0  4.576284      35.5        22.0       123.0        7.03   
5465        S    4.0  4.645130      35.0        13.0       120.0        7.25   

      shuttle  
2469     4.62  
313      4.45  
2444     4.29  
5610     4.14  
2971     4.58  
3004     4.51  
2607     4.62  
2283     4.33  
2412     4.40  
2449     4.51  
5237     4.18  
5590     3.99  
2665     4.69  
5997     4.25  
5465     4.37

Nice! All of the predicted 40-yard dash times have been filled into the dataset. Now let's remove the rows we have been operating on with missing 40-yard dash times in the orginal dataset and replace them with their updated counterparts that have filled in 40-yard dash times.

In [31]:
# Drop the rows we have been operating on with missing 40-yard dash times in the orginal dataset
missing_combine_data_2.drop(index=missing_fortys.index,inplace=True)

# Now we add the updated rows with filled-in 40-yard dash times.
missing_combine_data_2 = pd.concat([missing_combine_data_2, missing_fortys])

C:\Users\austy\AppData\Local\Temp\ipykernel_13028\601532866.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_combine_data_2.drop(index=missing_fortys.index,inplace=True)


In [32]:
# Check that there the amount of rows with missing forty values have been reduced by 15 because that is the size of the missing_fortys dataframe
missing_combine_data_2.isna().sum()

position         0
Round         2105
forty          362
vertical      1163
bench_reps    1820
broad_jump    1237
three_cone    2143
shuttle       2035
dtype: int64

Perfect! Now all of the 15 updated rows are in the original missing values dataset. There was 377 NA values in the 'forty' column, now there are 362. We could go a step further and merge the complete and missing dataframes back together just like we did earlier in the non-imputation section of this module, but you will instead be asked to build upon the missing dataset in the review questions below.

NOTE: We can also check that the columns have been correctly implemented by using a filter that is similar to the one we used to make the missing_fortys dataframe. However, this time we will include the 'forty' column in the list columns we want to be non-null because we filled in their estimated values. Take a look at the code below.

In [34]:
missing_combine_data_2[missing_combine_data_2[['forty','position', 'Round', 'vertical', 'bench_reps', 'broad_jump', 'three_cone', 'shuttle']].notna().all(axis=1)]

position  Round     forty  vertical  bench_reps  broad_jump  three_cone  \
313         C    4.0  5.071336      32.0        21.0        96.0        7.57   
2283       TE    5.0  4.717451      33.0        18.0       114.0        7.12   
2412        C    2.0  4.877402      30.5        21.0       108.0        7.29   
2444       RB    2.0  4.459857      40.0        11.0       126.0        7.07   
2449       RB    6.0  4.647741      35.0        15.0       120.0        7.13   
2469       OG    1.0  5.144127      26.5        35.0       105.0        7.65   
2607       OL    2.0  5.085281      28.0        29.0       109.0        7.77   
2665       OT    2.0  5.098020      28.0        27.0       108.0        7.77   
2971       OL    2.0  5.098342      26.5        33.0       105.0        7.53   
3004       OL    5.0  4.922348      30.5        25.0       112.0        7.50   
5237        S    5.0  4.519128      34.0        14.0       117.0        6.67   
5465        S    4.0  4.645130      35.0        13.0       120.0        7.25   
5590        S    2.0  4.551496      35.0        17.0       115.0        6.82   
5610       LB    5.0  4.473749      38.0        17.0       123.0        6.89   
5997       LB    3.0  4.576284      35.5        22.0       123.0        7.03   

      shuttle  
313      4.45  
2283     4.33  
2412     4.40  
2444     4.29  
2449     4.51  
2469     4.62  
2607     4.62  
2665     4.69  
2971     4.58  
3004     4.51  
5237     4.18  
5465     4.37  
5590     3.99  
5610     4.14  
5997     4.25

Nice! All 15 rows are present with their estimated 40-yard dash times.

--- 

# Review Questions

Still using the data we have used throughout this module, answer the following questions to review your knowledge!

### 1. Why would someone want to change the datatype of a column during the data cleaning process?

### 2. Re-read in the ORIGINAL dataset, split it into a complete and missing datasets like we did earlier. Find the median value of the 'bench_reps' column. Then, use that median value to fill in ALL of the NA values within that column. Check the number of NA values to make sure they are filled in correctly. 

HINT: use .median()

### 3. What does data completeness mean? List some appropriate ways you could achieve data completeness.

### 4. Which one of the three C's was not implemented in the following dataset? What could be done to fix it? 

| Position | Bench_Reps |
|----------|------------|
| TIGHT END |    35     |
| Quarterback |    25   |
| Tight End |    32     |
| Quarterback |   23    |

### 5. Use a linear regression model to predict 'bench_reps' for players who, we presume, did NOT participate in benching during the combine.